// ContextCallout (Q2.6) — the research archive as marginalia on live data.
//
// A quiet soft-surface sidebar card that places a VERIFIED passage from a published
// report or paper next to a live figure: a quote or fact, then a source line
// ("Report title, Year — from our research archive"). Every passage was
// quote-verified against the document it came from before shipping.
// `verbatim` renders the text in quotes; a paraphrase drops the quote marks and is
// clearly a summary. Kit-token themed (.ctx-* in index.css); decorative, never
// load-bearing for a claim.
//
// content/kb_callouts.json is GENERATED by site/tools/build_content.py from
// site/content_src/kb_callouts.source.json. The source carries a per-passage internal
// archive id for our own traceability; the generator strips it, because it resolves to
// nothing for a reader and CODE_DATA_FIRST_STANDARD s4.2 bars archive artefact
// references from reaching a visitor. Do not add it back to this component: it shipped
// visibly until W7, then in a title= attribute until 2026-07-25, and either way it was
// in the JS bundle. Edit the SOURCE, then re-run build_content.py.
import callouts from "../content/kb_callouts.json";

export interface KbCallout {
  id: string;
  /** where it mounts (page-side key, matched by the host page) */
  anchor: string;
  /** the passage — a quote (verbatim) or a marked paraphrase */
  text: string;
  /** true = exact quote from the doc (rendered in quotation marks) */
  verbatim: boolean;
  /** short source label, e.g. "NYC DOT Mobility Report" */
  source: string;
  /** publication year */
  year: number;
  /** optional one-line lead-in above the quote */
  lead?: string;
}

const ALL = callouts as KbCallout[];

/** All callouts curated for a given anchor (a page may show 1–2). */
export function calloutsFor(anchor: string): KbCallout[] {
  return ALL.filter((c) => c.anchor === anchor);
}

export default function ContextCallout({ c }: { c: KbCallout }) {
  return (
    <aside className="ctx-callout" aria-label={`Historical context: ${c.source}, ${c.year}`}>
      <div className="ctx-kicker">From the archive</div>
      {c.lead && <div className="ctx-lead">{c.lead}</div>}
      <blockquote className="ctx-quote">
        {c.verbatim ? <>&ldquo;{c.text}&rdquo;</> : c.text}
      </blockquote>
      <div className="ctx-src">
        {/* The reader's provenance is the published source and its year, both of which
            they can look up. The internal archive id that used to ride here (visibly
            until W7, then in a title= attribute) is stripped by build_content.py and
            never reaches the bundle. */}
        {c.source}, {c.year}{" "}
        <span className="ctx-kb">— from our research archive</span>
        {!c.verbatim && <span className="ctx-para"> (paraphrased)</span>}
      </div>
    </aside>
  );
}

/** Render every callout curated for an anchor (nothing if none). */
export function ContextCallouts({ anchor }: { anchor: string }) {
  const list = calloutsFor(anchor);
  if (!list.length) return null;
  return (
    <div className="ctx-stack">
      {list.map((c) => (
        <ContextCallout key={c.id} c={c} />
      ))}
    </div>
  );
}
